[package]
name = "textkit"
version = "0.1.1"
authors = ["Jevgeni Tarasov <jevgeni@hey.com>"]
edition = "2018"

[dependencies]
textkit-docx = { path = "../textkit-docx" }
clap = "3.0.0-beta.1"
serde = "^1"
serde_json = "^1"